name: trabajo_final
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
flutter:
  assets:
    - assets/img/ #Para las imagenes
  uses-material-design: true
