name: trabajo_final
description: "Trabajo final de flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

#Para los iconos en diferentes plataformas
flutter_launcher_icons:
  image_path: "assets/img/icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/img/icon.png"
    background_color: "#ffffff"
    theme_color: "#7B6CF6"
  windows:
    generate: true
    image_path: "assets/img/icon.png"
  macos:
    generate: true
    image_path: "assets/img/icon.png"

 
flutter:
  assets:
    - assets/img/ #Para las imagenes
  uses-material-design: true
